### ISSUE TITLE
exporting to JS might need some name mangling

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/js-interop-experimental#198]
I recall some issues when the Dart class has static methods that are banned in strict mode like "arguments" "caller" and "callee". Pretty obscure but might need name mangling to expose in JS.

**Comment by jmesserly** [comment]
(filed as a tracking issue after a chat with @jacob314)

**Comment by jacob314** [comment]
We're planning on using JS$ to mangle illegal JS names in dart. Perhaps we should use Dart$ to mangle Dart names

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/sdk#24886
