### ISSUE TITLE
RTE when using dart2js

### ISSUE THREAD

**Issue by frankpepermans** [dart-lang/js-interop-experimental#199]
Example:
Run all_tests.html from https://github.com/frankpepermans/rxdart/tree/master/test in both the Dart VM and as compiled to JS

- Dart VM: all tests pass
- Js: 3 'fail with invalid arguments' or 'method not found'

Using SDK 1.13.0-dev.7.2
Js: 0.6.0-beta-5

**Comment by kevmoo** [comment]
This issue was moved to dart-lang/sdk#24887
